### ISSUE TITLE
IPAD close dropdown issue

### ISSUE THREAD

**Issue by BilalW** [QODIO/selectator#20]
Hi

I noticed that once you open the dropdownlist on an IPAD it's not possible to close the dropdownlist again without selection something in the list first.

On desktop you can just click anywere else on the website and it will close the dropdownlist, but tapping anyway on the website on IPAD don't close the dropdown.

I tried on your test site and it's the same issue, but tapping the labels above the dropdown does close the dropdown though.

Isn't this a bug?

**Comment by jogvana** [comment]
Hi and thanks for the feedback. We'll get back asap.

Kindly
Jógvan

**Comment by BilalW** [comment]
Do you think that this is something that eventually will be fixed?:)

**Comment by BilalWachah** [comment]
?:)

**Comment by ingipingi** [comment]
This should be fixed now
