### ISSUE TITLE
Selectator not working on every reload

### ISSUE THREAD

**Issue by florianwaesch** [QODIO/selectator#23]
I like the selectator - really cool plugin. So I use it every time in my applications I need select-elements.
There is only one problem:

On a "normal" page the selectator works on every reload. If I have the selecator within a jQuery page which I get by load(), it doesn't work on every reload. If I refresh the page again, again and again, the selectator doesn't affect after x tries. The number of tries varies. In case of this problem there ist still no message in developer console or something - the element only stays the standard html select.

![selectator-not-working](https://user-images.githubusercontent.com/38833364/40885314-4bc64d1c-6724-11e8-963d-59f1fd6e5efd.jpg)

Is there some trick, or delay, or something else I can try? I still put the .selecator in a document ready function, but still the same problem.

**Comment by jogvana** [comment]
Hello Florian.

Ingi will look into this as soon as possible and get back.

Thanks for your patience and I'm glad the plugin is usable for you.

Kindly
Jógvan

**Comment by florianwaesch** [comment]
Hey @ingipingi this problem still exists... In the meantime I tried a few things by myself - no success.
I would be really happy if you've got some ideas. ;-)

**Comment by ingipingi** [comment]
Did you initiate it manually after the jQuery page loads?
You can do this by running `$('#selectBox').selectator();`
If it is already initiated, you could try destroying it first and then initiating it. 
`$('#selectBox').selectator('destroy');`
`$('#selectBox').selectator();`

**Comment by florianwaesch** [comment]
Oh dear... After I checked that and tried your advice, I got the error, that selecator is not a function.
I have forgotten to include/require the js-file in der loaded element. Now it works.
Thank you!!
