### ISSUE TITLE
placeholder does not work

### ISSUE THREAD

**Issue by biaderbia** [QODIO/selectator#24]
I use selector like this:
```
<select id="selectId" style="width: 100%;">
  <option value="1">One</option>
  <option value="2">Two</option>
</select>

function(){
  $selectId.selectator({
	useDimmer:true,
        placeholder:'Click to search...'
  });
};
```
Everything is ok, but the first option is selected after the page loads instead of displaying placeholder.
Why it does not work as expected, Am I missed something?

**Comment by ingipingi** [comment]
Like a standard html select box, when using singular select with local data, the select box shows the first option as selected.

**Comment by GrennKren** [comment]
If anyone has this problem..
You should give the selected option value=""  and not remove the value attribute.

Also, if you want hide the option element based on real option element you was hidding.
Insert this line into selectator js file..

```
// CREATE RESULT OPTION
var createOption = function (_isGroupOption) {
       //holder li
       var $option = $(document.createElement('li'));
       .
       .
       if($(this).css('display')=='none'){    //<<<<<<<<
           $option.addClass('hide');          //<<<<<<<<
       }                                      //<<<<<<<<
       .
       .
       // fetch data
	var data = {
	value: this.value,
	text : this.text
};
```
