### ISSUE TITLE
Selectator Dropdown not working properly on Safari

### ISSUE THREAD

**Issue by mdjunaidalam5** [QODIO/selectator#28]
While selecting option from the dropdown, the value is not getting updated, instead dropdown  shows selected item beneath the previous selection. The content is getting outside the element. 
<img width="1679" alt="selectator" src="https://user-images.githubusercontent.com/17555137/64491269-1c127b00-d284-11e9-9d83-f20e1d2d09db.png">

**Comment by jogvana** [comment]
Thanks for the feedback. We'll look into it asap.

**Comment by fdurna** [comment]
![answer](https://user-images.githubusercontent.com/15355851/69640539-91197380-106f-11ea-9521-289e5b336080.png)

thats's all
can you please try ?

**Comment by ingipingi** [comment]
Thanks, this has been corrected now
