### ISSUE TITLE
Can't click on an option with mouse

### ISSUE THREAD

**Issue by newmicha** [QODIO/selectator#31]
Hi, 
I found your script for showing pictures in a select element and like it much.
Unfortunately I can't make it run correctly. When using the script I can't click on an option from the drop down list. Also the mouse pointer won't change the appereance to the fingers like the pointer in the demo. When I choose an option with the keyboard it will work. Do you have an idea what could be the problem?

**Comment by jogvana** [comment]
Thanks for your valuable feedback. We'll look at this asap.

**Comment by newmicha** [comment]
I solved my problem. I placed the select element on a div/modal with a lower z-index than the options. Nevertheless many thanks.
